Feature/security keys (closes #225)
wisp-gg/frontend pull request #271
Opened 2022-05-01 02:21 UTC by victiondev

2022-05-01 09:02 UTC, TrixterTheTux requested changes

2022-05-02 13:24 UTC, TrixterTheTux requested changes

2022-05-02 13:24 UTC, TrixterTheTux commented on src/middlewares/index.ts
> +export { default as TOTP } from './required_2fa';
required_2fa filename should be `require_2fa`, and `default as TOTP` should use `Require2FA` instead of `TOTP` as the class name.

2022-05-02 13:24 UTC, TrixterTheTux commented on src/middlewares/required_2fa.ts
> +class Required2FA implements Middleware {
Require2FA

2022-05-02 13:24 UTC, TrixterTheTux commented on src/middlewares/required_2fa.ts
> +        return 'required_2fa';
require_2fa

2022-05-02 13:24 UTC, TrixterTheTux commented on src/views/account/2fa/Index.vue
> +            <div v-if="user.has2fa.includes('totp')">
See the first comment, has2fa could be a bool (in theory, though not in practice) making this confusing readability-wise.

2022-05-02 13:31 UTC, victiondev commented on src/views/admin/users/manage/About.vue
> +import Disable2faModal from "~/views/admin/users/manage/Disable2faModal.vue";
thanks webstorm :(

2022-05-02 13:47 UTC, TrixterTheTux approved these changes
LGTM

2022-05-02 13:55 UTC, merged